### ISSUE TITLE
你好，方便介绍一下自定义时间序列函数里的变量n吗？

### ISSUE THREAD

**Issue by bitallin** [chengwei-wang-ucsc/GPlearn_finiance_stock_futures_extension#2]
这个n是如何传入的 ？
为什么还要判断n[0] == n[1] and n[1] ==[2] ?

**Comment by chengwei-wang-ucsc** [comment]
你好，所有的” n[0] == n[1] and n[1] ==[2]”条件都是为了配合GPlearn在每轮拟合中会随机用到的常数数据。如下图红色圆圈部分所标注的常数项。

Hi, all the “ n[0] == n[1] and n[1] ==[2]” expressions are made because GPlearn will randomly introduce some constants into the final resulting equations. The constants are circled in the image below.

![88CBE20A-805E-4FDB-835E-23A84A1BCEBA](https://user-images.githubusercontent.com/97957369/199472995-fa8e1304-dd3f-4013-97a7-905cd51e1a2a.jpeg)

了解更多情况请见：
To know more about this, please see:

https://gplearn.readthedocs.io/en/stable/examples.html

**Comment by bitallin** [comment]
> 你好，所有的” n[0] == n[1] and n[1] ==[2]”条件都是为了配合GPlearn在每轮拟合中会随机用到的常数数据。如下图红色圆圈部分所标注的常数项。
> 
> Hi, all the “ n[0] == n[1] and n[1] ==[2]” expressions are made because GPlearn will randomly introduce some constants into the final resulting equations. The constants are circled in the image below.
> 
> ![88CBE20A-805E-4FDB-835E-23A84A1BCEBA](https://user-images.githubusercontent.com/97957369/199472995-fa8e1304-dd3f-4013-97a7-905cd51e1a2a.jpeg)
> 
> 了解更多情况请见： To know more about this, please see:
> 
> https://gplearn.readthedocs.io/en/stable/examples.html

非常感谢回复，还有一个疑问，那这里的的n或者d，是遗传算法每一轮拟合的时候随机分配一个常数项来计算，
那这个常数项是否就是完全随机的，它的取值范围大概在什么区间呢

**Comment by bitallin** [comment]
已经解决 谢谢
